//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/core-doppl/androidbase/src/main/java/android/database/sqlite/SQLiteFullException.java
//

#include "AndroidDatabaseSqliteSQLiteException.h"
#include "AndroidDatabaseSqliteSQLiteFullException.h"
#include "J2ObjC_source.h"

@implementation AndroidDatabaseSqliteSQLiteFullException

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  AndroidDatabaseSqliteSQLiteFullException_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)error {
  AndroidDatabaseSqliteSQLiteFullException_initWithNSString_(self, error);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LNSString;" };
  static const J2ObjcClassInfo _AndroidDatabaseSqliteSQLiteFullException = { "SQLiteFullException", "android.database.sqlite", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_AndroidDatabaseSqliteSQLiteFullException;
}

@end

void AndroidDatabaseSqliteSQLiteFullException_init(AndroidDatabaseSqliteSQLiteFullException *self) {
  AndroidDatabaseSqliteSQLiteException_init(self);
}

AndroidDatabaseSqliteSQLiteFullException *new_AndroidDatabaseSqliteSQLiteFullException_init() {
  J2OBJC_NEW_IMPL(AndroidDatabaseSqliteSQLiteFullException, init)
}

AndroidDatabaseSqliteSQLiteFullException *create_AndroidDatabaseSqliteSQLiteFullException_init() {
  J2OBJC_CREATE_IMPL(AndroidDatabaseSqliteSQLiteFullException, init)
}

void AndroidDatabaseSqliteSQLiteFullException_initWithNSString_(AndroidDatabaseSqliteSQLiteFullException *self, NSString *error) {
  AndroidDatabaseSqliteSQLiteException_initWithNSString_(self, error);
}

AndroidDatabaseSqliteSQLiteFullException *new_AndroidDatabaseSqliteSQLiteFullException_initWithNSString_(NSString *error) {
  J2OBJC_NEW_IMPL(AndroidDatabaseSqliteSQLiteFullException, initWithNSString_, error)
}

AndroidDatabaseSqliteSQLiteFullException *create_AndroidDatabaseSqliteSQLiteFullException_initWithNSString_(NSString *error) {
  J2OBJC_CREATE_IMPL(AndroidDatabaseSqliteSQLiteFullException, initWithNSString_, error)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AndroidDatabaseSqliteSQLiteFullException)
