//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/core-doppl/androidbase/src/main/java/rename/org/kxml2/io/KXmlParser.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RenameOrgKxml2IoKXmlParser")
#ifdef RESTRICT_RenameOrgKxml2IoKXmlParser
#define INCLUDE_ALL_RenameOrgKxml2IoKXmlParser 0
#else
#define INCLUDE_ALL_RenameOrgKxml2IoKXmlParser 1
#endif
#undef RESTRICT_RenameOrgKxml2IoKXmlParser

#if !defined (RenameOrgKxml2IoKXmlParser_) && (INCLUDE_ALL_RenameOrgKxml2IoKXmlParser || defined(INCLUDE_RenameOrgKxml2IoKXmlParser))
#define RenameOrgKxml2IoKXmlParser_

#define RESTRICT_OrgXmlpullV1XmlPullParser 1
#define INCLUDE_OrgXmlpullV1XmlPullParser 1
#include "org/xmlpull/v1/XmlPullParser.h"

#define RESTRICT_JavaIoCloseable 1
#define INCLUDE_JavaIoCloseable 1
#include "java/io/Closeable.h"

@class IOSCharArray;
@class IOSIntArray;
@class JavaIoInputStream;
@class JavaIoReader;
@class RenameLibcoreInternalStringPool;

@interface RenameOrgKxml2IoKXmlParser : NSObject < OrgXmlpullV1XmlPullParser, JavaIoCloseable > {
 @public
  RenameLibcoreInternalStringPool *stringPool_;
}

#pragma mark Public

- (instancetype)init;

- (void)close;

- (void)defineEntityReplacementTextWithNSString:(NSString *)entity
                                   withNSString:(NSString *)value;

- (jint)getAttributeCount;

- (NSString *)getAttributeNameWithInt:(jint)index;

- (NSString *)getAttributeNamespaceWithInt:(jint)index;

- (NSString *)getAttributePrefixWithInt:(jint)index;

- (NSString *)getAttributeTypeWithInt:(jint)index;

- (NSString *)getAttributeValueWithInt:(jint)index;

- (NSString *)getAttributeValueWithNSString:(NSString *)namespace_
                               withNSString:(NSString *)name;

- (jint)getColumnNumber;

- (jint)getDepth;

- (jint)getEventType;

- (jboolean)getFeatureWithNSString:(NSString *)feature;

- (NSString *)getInputEncoding;

- (jint)getLineNumber;

- (NSString *)getName;

- (NSString *)getNamespace;

- (NSString *)getNamespaceWithNSString:(NSString *)prefix;

- (jint)getNamespaceCountWithInt:(jint)depth;

- (NSString *)getNamespacePrefixWithInt:(jint)pos;

- (NSString *)getNamespaceUriWithInt:(jint)pos;

- (NSString *)getPositionDescription;

- (NSString *)getPrefix;

- (id)getPropertyWithNSString:(NSString *)property;

- (NSString *)getPublicId;

- (NSString *)getRootElementName;

- (NSString *)getSystemId;

- (NSString *)getText;

- (IOSCharArray *)getTextCharactersWithIntArray:(IOSIntArray *)poslen;

- (jboolean)isAttributeDefaultWithInt:(jint)index;

- (jboolean)isEmptyElementTag;

- (jboolean)isWhitespace;

- (void)keepNamespaceAttributes;

- (jint)next;

- (jint)nextTag;

- (NSString *)nextText;

- (jint)nextToken;

- (void)requireWithInt:(jint)type
          withNSString:(NSString *)namespace_
          withNSString:(NSString *)name;

- (void)setFeatureWithNSString:(NSString *)feature
                   withBoolean:(jboolean)value;

- (void)setInputWithJavaIoInputStream:(JavaIoInputStream *)is
                         withNSString:(NSString *)charset;

- (void)setInputWithJavaIoReader:(JavaIoReader *)reader;

- (void)setPropertyWithNSString:(NSString *)property
                         withId:(id)value;

@end

J2OBJC_STATIC_INIT(RenameOrgKxml2IoKXmlParser)

J2OBJC_FIELD_SETTER(RenameOrgKxml2IoKXmlParser, stringPool_, RenameLibcoreInternalStringPool *)

FOUNDATION_EXPORT void RenameOrgKxml2IoKXmlParser_init(RenameOrgKxml2IoKXmlParser *self);

FOUNDATION_EXPORT RenameOrgKxml2IoKXmlParser *new_RenameOrgKxml2IoKXmlParser_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RenameOrgKxml2IoKXmlParser *create_RenameOrgKxml2IoKXmlParser_init();

J2OBJC_TYPE_LITERAL_HEADER(RenameOrgKxml2IoKXmlParser)

#endif

#if !defined (RenameOrgKxml2IoKXmlParser_ValueContext_) && (INCLUDE_ALL_RenameOrgKxml2IoKXmlParser || defined(INCLUDE_RenameOrgKxml2IoKXmlParser_ValueContext))
#define RenameOrgKxml2IoKXmlParser_ValueContext_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, RenameOrgKxml2IoKXmlParser_ValueContext_Enum) {
  RenameOrgKxml2IoKXmlParser_ValueContext_Enum_ATTRIBUTE = 0,
  RenameOrgKxml2IoKXmlParser_ValueContext_Enum_TEXT = 1,
  RenameOrgKxml2IoKXmlParser_ValueContext_Enum_ENTITY_DECLARATION = 2,
};

@interface RenameOrgKxml2IoKXmlParser_ValueContext : JavaLangEnum < NSCopying >

#pragma mark Public

+ (RenameOrgKxml2IoKXmlParser_ValueContext *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(RenameOrgKxml2IoKXmlParser_ValueContext)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT RenameOrgKxml2IoKXmlParser_ValueContext *RenameOrgKxml2IoKXmlParser_ValueContext_values_[];

inline RenameOrgKxml2IoKXmlParser_ValueContext *RenameOrgKxml2IoKXmlParser_ValueContext_get_ATTRIBUTE();
J2OBJC_ENUM_CONSTANT(RenameOrgKxml2IoKXmlParser_ValueContext, ATTRIBUTE)

inline RenameOrgKxml2IoKXmlParser_ValueContext *RenameOrgKxml2IoKXmlParser_ValueContext_get_TEXT();
J2OBJC_ENUM_CONSTANT(RenameOrgKxml2IoKXmlParser_ValueContext, TEXT)

inline RenameOrgKxml2IoKXmlParser_ValueContext *RenameOrgKxml2IoKXmlParser_ValueContext_get_ENTITY_DECLARATION();
J2OBJC_ENUM_CONSTANT(RenameOrgKxml2IoKXmlParser_ValueContext, ENTITY_DECLARATION)

FOUNDATION_EXPORT IOSObjectArray *RenameOrgKxml2IoKXmlParser_ValueContext_values();

FOUNDATION_EXPORT RenameOrgKxml2IoKXmlParser_ValueContext *RenameOrgKxml2IoKXmlParser_ValueContext_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT RenameOrgKxml2IoKXmlParser_ValueContext *RenameOrgKxml2IoKXmlParser_ValueContext_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(RenameOrgKxml2IoKXmlParser_ValueContext)

#endif

#if !defined (RenameOrgKxml2IoKXmlParser_ContentSource_) && (INCLUDE_ALL_RenameOrgKxml2IoKXmlParser || defined(INCLUDE_RenameOrgKxml2IoKXmlParser_ContentSource))
#define RenameOrgKxml2IoKXmlParser_ContentSource_

@class IOSCharArray;

@interface RenameOrgKxml2IoKXmlParser_ContentSource : NSObject

#pragma mark Package-Private

- (instancetype)initWithRenameOrgKxml2IoKXmlParser_ContentSource:(RenameOrgKxml2IoKXmlParser_ContentSource *)next
                                                   withCharArray:(IOSCharArray *)buffer
                                                         withInt:(jint)position
                                                         withInt:(jint)limit;

@end

J2OBJC_EMPTY_STATIC_INIT(RenameOrgKxml2IoKXmlParser_ContentSource)

FOUNDATION_EXPORT void RenameOrgKxml2IoKXmlParser_ContentSource_initWithRenameOrgKxml2IoKXmlParser_ContentSource_withCharArray_withInt_withInt_(RenameOrgKxml2IoKXmlParser_ContentSource *self, RenameOrgKxml2IoKXmlParser_ContentSource *next, IOSCharArray *buffer, jint position, jint limit);

FOUNDATION_EXPORT RenameOrgKxml2IoKXmlParser_ContentSource *new_RenameOrgKxml2IoKXmlParser_ContentSource_initWithRenameOrgKxml2IoKXmlParser_ContentSource_withCharArray_withInt_withInt_(RenameOrgKxml2IoKXmlParser_ContentSource *next, IOSCharArray *buffer, jint position, jint limit) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RenameOrgKxml2IoKXmlParser_ContentSource *create_RenameOrgKxml2IoKXmlParser_ContentSource_initWithRenameOrgKxml2IoKXmlParser_ContentSource_withCharArray_withInt_withInt_(RenameOrgKxml2IoKXmlParser_ContentSource *next, IOSCharArray *buffer, jint position, jint limit);

J2OBJC_TYPE_LITERAL_HEADER(RenameOrgKxml2IoKXmlParser_ContentSource)

#endif

#pragma pop_macro("INCLUDE_ALL_RenameOrgKxml2IoKXmlParser")
