//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/core-doppl/androidbase/src/main/java/rename/com/android/internal/util/FastXmlSerializer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RenameComAndroidInternalUtilFastXmlSerializer")
#ifdef RESTRICT_RenameComAndroidInternalUtilFastXmlSerializer
#define INCLUDE_ALL_RenameComAndroidInternalUtilFastXmlSerializer 0
#else
#define INCLUDE_ALL_RenameComAndroidInternalUtilFastXmlSerializer 1
#endif
#undef RESTRICT_RenameComAndroidInternalUtilFastXmlSerializer

#if !defined (RenameComAndroidInternalUtilFastXmlSerializer_) && (INCLUDE_ALL_RenameComAndroidInternalUtilFastXmlSerializer || defined(INCLUDE_RenameComAndroidInternalUtilFastXmlSerializer))
#define RenameComAndroidInternalUtilFastXmlSerializer_

#define RESTRICT_OrgXmlpullV1XmlSerializer 1
#define INCLUDE_OrgXmlpullV1XmlSerializer 1
#include "org/xmlpull/v1/XmlSerializer.h"

@class IOSCharArray;
@class JavaIoOutputStream;
@class JavaIoWriter;
@class JavaLangBoolean;

@interface RenameComAndroidInternalUtilFastXmlSerializer : NSObject < OrgXmlpullV1XmlSerializer >

#pragma mark Public

- (instancetype)init;

- (id<OrgXmlpullV1XmlSerializer>)attributeWithNSString:(NSString *)namespace_
                                          withNSString:(NSString *)name
                                          withNSString:(NSString *)value;

- (void)cdsectWithNSString:(NSString *)text;

- (void)commentWithNSString:(NSString *)text;

- (void)docdeclWithNSString:(NSString *)text;

- (void)endDocument;

- (id<OrgXmlpullV1XmlSerializer>)endTagWithNSString:(NSString *)namespace_
                                       withNSString:(NSString *)name;

- (void)entityRefWithNSString:(NSString *)text;

- (void)flush;

- (jint)getDepth;

- (jboolean)getFeatureWithNSString:(NSString *)name;

- (NSString *)getName;

- (NSString *)getNamespace;

- (NSString *)getPrefixWithNSString:(NSString *)namespace_
                        withBoolean:(jboolean)generatePrefix;

- (id)getPropertyWithNSString:(NSString *)name;

- (void)ignorableWhitespaceWithNSString:(NSString *)text;

- (void)processingInstructionWithNSString:(NSString *)text;

- (void)setFeatureWithNSString:(NSString *)name
                   withBoolean:(jboolean)state;

- (void)setOutputWithJavaIoOutputStream:(JavaIoOutputStream *)os
                           withNSString:(NSString *)encoding;

- (void)setOutputWithJavaIoWriter:(JavaIoWriter *)writer;

- (void)setPrefixWithNSString:(NSString *)prefix
                 withNSString:(NSString *)namespace_;

- (void)setPropertyWithNSString:(NSString *)name
                         withId:(id)value;

- (void)startDocumentWithNSString:(NSString *)encoding
              withJavaLangBoolean:(JavaLangBoolean *)standalone;

- (id<OrgXmlpullV1XmlSerializer>)startTagWithNSString:(NSString *)namespace_
                                         withNSString:(NSString *)name;

- (id<OrgXmlpullV1XmlSerializer>)textWithCharArray:(IOSCharArray *)buf
                                           withInt:(jint)start
                                           withInt:(jint)len;

- (id<OrgXmlpullV1XmlSerializer>)textWithNSString:(NSString *)text;

@end

J2OBJC_STATIC_INIT(RenameComAndroidInternalUtilFastXmlSerializer)

FOUNDATION_EXPORT void RenameComAndroidInternalUtilFastXmlSerializer_init(RenameComAndroidInternalUtilFastXmlSerializer *self);

FOUNDATION_EXPORT RenameComAndroidInternalUtilFastXmlSerializer *new_RenameComAndroidInternalUtilFastXmlSerializer_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RenameComAndroidInternalUtilFastXmlSerializer *create_RenameComAndroidInternalUtilFastXmlSerializer_init();

J2OBJC_TYPE_LITERAL_HEADER(RenameComAndroidInternalUtilFastXmlSerializer)

#endif

#pragma pop_macro("INCLUDE_ALL_RenameComAndroidInternalUtilFastXmlSerializer")
