//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/RxJava/src/test/java/rx/doppl/mock/MAction1.java
//

#include "J2ObjC_source.h"
#include "RxDopplMockMAction1.h"

@implementation RxDopplMockMAction1

- (void)callWithId:(id)t {
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  RxDopplMockMAction1_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x1, 0, 1, -1, 2, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(callWithId:);
  methods[1].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "call", "LNSObject;", "(TT;)V", "<T:Ljava/lang/Object;>Ljava/lang/Object;Lrx/functions/Action1<TT;>;" };
  static const J2ObjcClassInfo _RxDopplMockMAction1 = { "MAction1", "rx.doppl.mock", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, 3, -1 };
  return &_RxDopplMockMAction1;
}

@end

void RxDopplMockMAction1_init(RxDopplMockMAction1 *self) {
  NSObject_init(self);
}

RxDopplMockMAction1 *new_RxDopplMockMAction1_init() {
  J2OBJC_NEW_IMPL(RxDopplMockMAction1, init)
}

RxDopplMockMAction1 *create_RxDopplMockMAction1_init() {
  J2OBJC_CREATE_IMPL(RxDopplMockMAction1, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RxDopplMockMAction1)
