//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/RxJava/src/test/java/rx/exceptions/ExceptionsNullTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RxExceptionsExceptionsNullTest")
#ifdef RESTRICT_RxExceptionsExceptionsNullTest
#define INCLUDE_ALL_RxExceptionsExceptionsNullTest 0
#else
#define INCLUDE_ALL_RxExceptionsExceptionsNullTest 1
#endif
#undef RESTRICT_RxExceptionsExceptionsNullTest

#if !defined (RxExceptionsExceptionsNullTest_) && (INCLUDE_ALL_RxExceptionsExceptionsNullTest || defined(INCLUDE_RxExceptionsExceptionsNullTest))
#define RxExceptionsExceptionsNullTest_

@interface RxExceptionsExceptionsNullTest : NSObject

#pragma mark Public

- (instancetype)init;

- (void)testOnCompleteFailedExceptionMessageAndNull;

- (void)testOnCompleteFailedExceptionNull;

- (void)testOnErrorFailedExceptionMessageAndNull;

- (void)testOnErrorFailedExceptionNull;

- (void)testOnErrorNotImplementedExceptionMessageAndNull;

- (void)testOnErrorNotImplementedExceptionNull;

- (void)testOnErrorThrowableAddValueAsLastCause;

- (void)testOnErrorThrowableFrom;

- (void)testUnsubscribeFailedExceptionMessageAndNull;

- (void)testUnsubscribeFailedExceptionNull;

@end

J2OBJC_EMPTY_STATIC_INIT(RxExceptionsExceptionsNullTest)

FOUNDATION_EXPORT void RxExceptionsExceptionsNullTest_init(RxExceptionsExceptionsNullTest *self);

FOUNDATION_EXPORT RxExceptionsExceptionsNullTest *new_RxExceptionsExceptionsNullTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxExceptionsExceptionsNullTest *create_RxExceptionsExceptionsNullTest_init();

J2OBJC_TYPE_LITERAL_HEADER(RxExceptionsExceptionsNullTest)

#endif

#pragma pop_macro("INCLUDE_ALL_RxExceptionsExceptionsNullTest")
