//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/RxJava/src/test/java/rx/internal/operators/BlockingOperatorMostRecentTest.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "RxExceptionsTestException.h"
#include "RxInternalOperatorsBlockingOperatorMostRecent.h"
#include "RxInternalOperatorsBlockingOperatorMostRecentTest.h"
#include "RxObservable.h"
#include "RxObservablesBlockingObservable.h"
#include "RxSchedulersTestScheduler.h"
#include "RxSubjectsPublishSubject.h"
#include "RxSubjectsSubject.h"
#include "RxTestUtil.h"
#include "java/lang/Boolean.h"
#include "java/lang/Iterable.h"
#include "java/lang/Long.h"
#include "java/lang/Void.h"
#include "java/lang/annotation/Annotation.h"
#include "java/util/Iterator.h"
#include "java/util/concurrent/TimeUnit.h"
#include "org/junit/Assert.h"
#include "org/junit/Test.h"

__attribute__((unused)) static IOSObjectArray *RxInternalOperatorsBlockingOperatorMostRecentTest__Annotations$0();

__attribute__((unused)) static IOSObjectArray *RxInternalOperatorsBlockingOperatorMostRecentTest__Annotations$1();

__attribute__((unused)) static IOSObjectArray *RxInternalOperatorsBlockingOperatorMostRecentTest__Annotations$2();

__attribute__((unused)) static IOSObjectArray *RxInternalOperatorsBlockingOperatorMostRecentTest__Annotations$3();

__attribute__((unused)) static IOSObjectArray *RxInternalOperatorsBlockingOperatorMostRecentTest__Annotations$4();

@implementation RxInternalOperatorsBlockingOperatorMostRecentTest

- (void)constructorShouldBePrivate {
  RxTestUtil_checkUtilityClassWithIOSClass_(RxInternalOperatorsBlockingOperatorMostRecent_class_());
}

- (void)testMostRecentNull {
  OrgJunitAssert_assertEqualsWithId_withId_(nil, [((id<JavaUtilIterator>) nil_chk([((id<JavaLangIterable>) nil_chk([((RxObservablesBlockingObservable *) nil_chk([((RxObservable *) nil_chk(RxObservable_never())) toBlocking])) mostRecentWithId:nil])) iterator])) next]);
}

- (void)testMostRecent {
  RxSubjectsSubject *s = RxSubjectsPublishSubject_create();
  id<JavaUtilIterator> it = [((id<JavaLangIterable>) nil_chk(RxInternalOperatorsBlockingOperatorMostRecent_mostRecentWithRxObservable_withId_(s, @"default"))) iterator];
  OrgJunitAssert_assertTrueWithBoolean_([((id<JavaUtilIterator>) nil_chk(it)) hasNext]);
  OrgJunitAssert_assertEqualsWithId_withId_(@"default", [it next]);
  OrgJunitAssert_assertEqualsWithId_withId_(@"default", [it next]);
  [((RxSubjectsSubject *) nil_chk(s)) onNextWithId:@"one"];
  OrgJunitAssert_assertTrueWithBoolean_([it hasNext]);
  OrgJunitAssert_assertEqualsWithId_withId_(@"one", [it next]);
  OrgJunitAssert_assertEqualsWithId_withId_(@"one", [it next]);
  [s onNextWithId:@"two"];
  OrgJunitAssert_assertTrueWithBoolean_([it hasNext]);
  OrgJunitAssert_assertEqualsWithId_withId_(@"two", [it next]);
  OrgJunitAssert_assertEqualsWithId_withId_(@"two", [it next]);
  [s onCompleted];
  OrgJunitAssert_assertFalseWithBoolean_([it hasNext]);
}

- (void)testMostRecentWithException {
  RxSubjectsSubject *s = RxSubjectsPublishSubject_create();
  id<JavaUtilIterator> it = [((id<JavaLangIterable>) nil_chk(RxInternalOperatorsBlockingOperatorMostRecent_mostRecentWithRxObservable_withId_(s, @"default"))) iterator];
  OrgJunitAssert_assertTrueWithBoolean_([((id<JavaUtilIterator>) nil_chk(it)) hasNext]);
  OrgJunitAssert_assertEqualsWithId_withId_(@"default", [it next]);
  OrgJunitAssert_assertEqualsWithId_withId_(@"default", [it next]);
  [((RxSubjectsSubject *) nil_chk(s)) onErrorWithNSException:create_RxExceptionsTestException_init()];
  OrgJunitAssert_assertTrueWithBoolean_([it hasNext]);
  [it next];
}

- (void)testSingleSourceManyIterators {
  RxSchedulersTestScheduler *scheduler = create_RxSchedulersTestScheduler_init();
  RxObservablesBlockingObservable *source = [((RxObservable *) nil_chk([((RxObservable *) nil_chk(RxObservable_intervalWithLong_withJavaUtilConcurrentTimeUnit_withRxScheduler_(1, JreLoadEnum(JavaUtilConcurrentTimeUnit, SECONDS), scheduler))) takeWithInt:10])) toBlocking];
  id<JavaLangIterable> iter = [((RxObservablesBlockingObservable *) nil_chk(source)) mostRecentWithId:JavaLangLong_valueOfWithLong_(-1LL)];
  for (jint j = 0; j < 3; j++) {
    id<JavaUtilIterator> it = [((id<JavaLangIterable>) nil_chk(iter)) iterator];
    OrgJunitAssert_assertEqualsWithId_withId_(JavaLangLong_valueOfWithLong_(-1), [((id<JavaUtilIterator>) nil_chk(it)) next]);
    for (jint i = 0; i < 9; i++) {
      [scheduler advanceTimeByWithLong:1 withJavaUtilConcurrentTimeUnit:JreLoadEnum(JavaUtilConcurrentTimeUnit, SECONDS)];
      OrgJunitAssert_assertEqualsWithId_withId_(JavaLangBoolean_valueOfWithBoolean_(true), JavaLangBoolean_valueOfWithBoolean_([it hasNext]));
      OrgJunitAssert_assertEqualsWithId_withId_(JavaLangLong_valueOfWithLong_(i), [it next]);
    }
    [scheduler advanceTimeByWithLong:1 withJavaUtilConcurrentTimeUnit:JreLoadEnum(JavaUtilConcurrentTimeUnit, SECONDS)];
    OrgJunitAssert_assertEqualsWithId_withId_(JavaLangBoolean_valueOfWithBoolean_(false), JavaLangBoolean_valueOfWithBoolean_([it hasNext]));
  }
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  RxInternalOperatorsBlockingOperatorMostRecentTest_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x1, -1, -1, -1, -1, 0, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, 1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, 2, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, 3, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, 4, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(constructorShouldBePrivate);
  methods[1].selector = @selector(testMostRecentNull);
  methods[2].selector = @selector(testMostRecent);
  methods[3].selector = @selector(testMostRecentWithException);
  methods[4].selector = @selector(testSingleSourceManyIterators);
  methods[5].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { (void *)&RxInternalOperatorsBlockingOperatorMostRecentTest__Annotations$0, (void *)&RxInternalOperatorsBlockingOperatorMostRecentTest__Annotations$1, (void *)&RxInternalOperatorsBlockingOperatorMostRecentTest__Annotations$2, (void *)&RxInternalOperatorsBlockingOperatorMostRecentTest__Annotations$3, (void *)&RxInternalOperatorsBlockingOperatorMostRecentTest__Annotations$4 };
  static const J2ObjcClassInfo _RxInternalOperatorsBlockingOperatorMostRecentTest = { "BlockingOperatorMostRecentTest", "rx.internal.operators", ptrTable, methods, NULL, 7, 0x1, 6, 0, -1, -1, -1, -1, -1 };
  return &_RxInternalOperatorsBlockingOperatorMostRecentTest;
}

@end

void RxInternalOperatorsBlockingOperatorMostRecentTest_init(RxInternalOperatorsBlockingOperatorMostRecentTest *self) {
  NSObject_init(self);
}

RxInternalOperatorsBlockingOperatorMostRecentTest *new_RxInternalOperatorsBlockingOperatorMostRecentTest_init() {
  J2OBJC_NEW_IMPL(RxInternalOperatorsBlockingOperatorMostRecentTest, init)
}

RxInternalOperatorsBlockingOperatorMostRecentTest *create_RxInternalOperatorsBlockingOperatorMostRecentTest_init() {
  J2OBJC_CREATE_IMPL(RxInternalOperatorsBlockingOperatorMostRecentTest, init)
}

IOSObjectArray *RxInternalOperatorsBlockingOperatorMostRecentTest__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *RxInternalOperatorsBlockingOperatorMostRecentTest__Annotations$1() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *RxInternalOperatorsBlockingOperatorMostRecentTest__Annotations$2() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *RxInternalOperatorsBlockingOperatorMostRecentTest__Annotations$3() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(RxExceptionsTestException_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *RxInternalOperatorsBlockingOperatorMostRecentTest__Annotations$4() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 1000) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RxInternalOperatorsBlockingOperatorMostRecentTest)
