//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/RxJava/src/test/java/rx/internal/util/LinkedArrayListTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RxInternalUtilLinkedArrayListTest")
#ifdef RESTRICT_RxInternalUtilLinkedArrayListTest
#define INCLUDE_ALL_RxInternalUtilLinkedArrayListTest 0
#else
#define INCLUDE_ALL_RxInternalUtilLinkedArrayListTest 1
#endif
#undef RESTRICT_RxInternalUtilLinkedArrayListTest

#if !defined (RxInternalUtilLinkedArrayListTest_) && (INCLUDE_ALL_RxInternalUtilLinkedArrayListTest || defined(INCLUDE_RxInternalUtilLinkedArrayListTest))
#define RxInternalUtilLinkedArrayListTest_

@interface RxInternalUtilLinkedArrayListTest : NSObject

#pragma mark Public

- (instancetype)init;

- (void)testAdd;

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalUtilLinkedArrayListTest)

FOUNDATION_EXPORT void RxInternalUtilLinkedArrayListTest_init(RxInternalUtilLinkedArrayListTest *self);

FOUNDATION_EXPORT RxInternalUtilLinkedArrayListTest *new_RxInternalUtilLinkedArrayListTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxInternalUtilLinkedArrayListTest *create_RxInternalUtilLinkedArrayListTest_init();

J2OBJC_TYPE_LITERAL_HEADER(RxInternalUtilLinkedArrayListTest)

#endif

#pragma pop_macro("INCLUDE_ALL_RxInternalUtilLinkedArrayListTest")
