//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/RxJava/src/test/java/rx/schedulers/GenericScheduledExecutorServiceTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RxSchedulersGenericScheduledExecutorServiceTest")
#ifdef RESTRICT_RxSchedulersGenericScheduledExecutorServiceTest
#define INCLUDE_ALL_RxSchedulersGenericScheduledExecutorServiceTest 0
#else
#define INCLUDE_ALL_RxSchedulersGenericScheduledExecutorServiceTest 1
#endif
#undef RESTRICT_RxSchedulersGenericScheduledExecutorServiceTest

#if !defined (RxSchedulersGenericScheduledExecutorServiceTest_) && (INCLUDE_ALL_RxSchedulersGenericScheduledExecutorServiceTest || defined(INCLUDE_RxSchedulersGenericScheduledExecutorServiceTest))
#define RxSchedulersGenericScheduledExecutorServiceTest_

@interface RxSchedulersGenericScheduledExecutorServiceTest : NSObject

#pragma mark Public

- (instancetype)init;

- (void)genericScheduledExecutorServiceHook;

@end

J2OBJC_EMPTY_STATIC_INIT(RxSchedulersGenericScheduledExecutorServiceTest)

FOUNDATION_EXPORT void RxSchedulersGenericScheduledExecutorServiceTest_init(RxSchedulersGenericScheduledExecutorServiceTest *self);

FOUNDATION_EXPORT RxSchedulersGenericScheduledExecutorServiceTest *new_RxSchedulersGenericScheduledExecutorServiceTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxSchedulersGenericScheduledExecutorServiceTest *create_RxSchedulersGenericScheduledExecutorServiceTest_init();

J2OBJC_TYPE_LITERAL_HEADER(RxSchedulersGenericScheduledExecutorServiceTest)

#endif

#pragma pop_macro("INCLUDE_ALL_RxSchedulersGenericScheduledExecutorServiceTest")
