//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/core-doppl/androidbasetest/src/main/java/co/touchlab/doppel/testing/MockGen.java
//

#include "CoTouchlabDoppelTestingMockGen.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/annotation/Annotation.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Target.h"

@interface CoTouchlabDoppelTestingMockGen : NSObject

@end

__attribute__((unused)) static IOSObjectArray *CoTouchlabDoppelTestingMockGen__Annotations$0();

@implementation CoTouchlabDoppelTestingMockGen

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "[LNSString;", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(classes);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { (void *)&CoTouchlabDoppelTestingMockGen__Annotations$0 };
  static const J2ObjcClassInfo _CoTouchlabDoppelTestingMockGen = { "MockGen", "co.touchlab.doppel.testing", ptrTable, methods, NULL, 7, 0x2609, 1, 0, -1, -1, -1, -1, 0 };
  return &_CoTouchlabDoppelTestingMockGen;
}

@end

IOSObjectArray *CoTouchlabDoppelTestingMockGen__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaLangAnnotationTarget([IOSObjectArray arrayWithObjects:(id[]){ JreLoadEnum(JavaLangAnnotationElementType, TYPE) } count:1 type:NSObject_class_()]) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(CoTouchlabDoppelTestingMockGen)
