//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/RxJava/src/main/java/rx/functions/Func3.java
//

#include "J2ObjC_source.h"
#include "RxFunctionsFunc3.h"

@interface RxFunctionsFunc3 : NSObject

@end

@implementation RxFunctionsFunc3

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSObject;", 0x401, 0, 1, -1, 2, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(callWithId:withId:withId:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "call", "LNSObject;LNSObject;LNSObject;", "(TT1;TT2;TT3;)TR;", "<T1:Ljava/lang/Object;T2:Ljava/lang/Object;T3:Ljava/lang/Object;R:Ljava/lang/Object;>Ljava/lang/Object;Lrx/functions/Function;" };
  static const J2ObjcClassInfo _RxFunctionsFunc3 = { "Func3", "rx.functions", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, 3, -1 };
  return &_RxFunctionsFunc3;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RxFunctionsFunc3)
