//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/RxJava/src/main/java/rx/internal/operators/OperatorElementAt.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "RxInternalOperatorsOperatorElementAt.h"
#include "RxProducer.h"
#include "RxSubscriber.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/IndexOutOfBoundsException.h"
#include "java/lang/Long.h"
#include "java/util/concurrent/atomic/AtomicBoolean.h"

@interface RxInternalOperatorsOperatorElementAt ()

- (instancetype)initWithInt:(jint)index
                     withId:(id)defaultValue
                withBoolean:(jboolean)hasDefault;

@end

__attribute__((unused)) static void RxInternalOperatorsOperatorElementAt_initWithInt_withId_withBoolean_(RxInternalOperatorsOperatorElementAt *self, jint index, id defaultValue, jboolean hasDefault);

__attribute__((unused)) static RxInternalOperatorsOperatorElementAt *new_RxInternalOperatorsOperatorElementAt_initWithInt_withId_withBoolean_(jint index, id defaultValue, jboolean hasDefault) NS_RETURNS_RETAINED;

__attribute__((unused)) static RxInternalOperatorsOperatorElementAt *create_RxInternalOperatorsOperatorElementAt_initWithInt_withId_withBoolean_(jint index, id defaultValue, jboolean hasDefault);

inline jlong RxInternalOperatorsOperatorElementAt_InnerProducer_get_serialVersionUID();
#define RxInternalOperatorsOperatorElementAt_InnerProducer_serialVersionUID 1LL
J2OBJC_STATIC_FIELD_CONSTANT(RxInternalOperatorsOperatorElementAt_InnerProducer, serialVersionUID, jlong)

@interface RxInternalOperatorsOperatorElementAt_$1 : RxSubscriber {
 @public
  RxInternalOperatorsOperatorElementAt *this$0_;
  jint currentIndex_;
  RxSubscriber *val$child_;
}

- (void)onNextWithId:(id)value;

- (void)onErrorWithNSException:(NSException *)e;

- (void)onCompleted;

- (void)setProducerWithRxProducer:(id<RxProducer>)p;

- (instancetype)initWithRxInternalOperatorsOperatorElementAt:(RxInternalOperatorsOperatorElementAt *)outer$
                                            withRxSubscriber:(RxSubscriber *)capture$0;

@end

J2OBJC_EMPTY_STATIC_INIT(RxInternalOperatorsOperatorElementAt_$1)

J2OBJC_FIELD_SETTER(RxInternalOperatorsOperatorElementAt_$1, this$0_, RxInternalOperatorsOperatorElementAt *)
J2OBJC_FIELD_SETTER(RxInternalOperatorsOperatorElementAt_$1, val$child_, RxSubscriber *)

__attribute__((unused)) static void RxInternalOperatorsOperatorElementAt_$1_initWithRxInternalOperatorsOperatorElementAt_withRxSubscriber_(RxInternalOperatorsOperatorElementAt_$1 *self, RxInternalOperatorsOperatorElementAt *outer$, RxSubscriber *capture$0);

__attribute__((unused)) static RxInternalOperatorsOperatorElementAt_$1 *new_RxInternalOperatorsOperatorElementAt_$1_initWithRxInternalOperatorsOperatorElementAt_withRxSubscriber_(RxInternalOperatorsOperatorElementAt *outer$, RxSubscriber *capture$0) NS_RETURNS_RETAINED;

__attribute__((unused)) static RxInternalOperatorsOperatorElementAt_$1 *create_RxInternalOperatorsOperatorElementAt_$1_initWithRxInternalOperatorsOperatorElementAt_withRxSubscriber_(RxInternalOperatorsOperatorElementAt *outer$, RxSubscriber *capture$0);

@implementation RxInternalOperatorsOperatorElementAt

- (instancetype)initWithInt:(jint)index {
  RxInternalOperatorsOperatorElementAt_initWithInt_(self, index);
  return self;
}

- (instancetype)initWithInt:(jint)index
                     withId:(id)defaultValue {
  RxInternalOperatorsOperatorElementAt_initWithInt_withId_(self, index, defaultValue);
  return self;
}

- (instancetype)initWithInt:(jint)index
                     withId:(id)defaultValue
                withBoolean:(jboolean)hasDefault {
  RxInternalOperatorsOperatorElementAt_initWithInt_withId_withBoolean_(self, index, defaultValue, hasDefault);
  return self;
}

- (RxSubscriber *)callWithId:(RxSubscriber *)child {
  RxSubscriber *parent = create_RxInternalOperatorsOperatorElementAt_$1_initWithRxInternalOperatorsOperatorElementAt_withRxSubscriber_(self, child);
  [((RxSubscriber *) nil_chk(child)) addWithRxSubscription:parent];
  return parent;
}

- (void)dealloc {
  RELEASE_(defaultValue_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, 2, -1, -1 },
    { NULL, NULL, 0x2, -1, 3, -1, 4, -1, -1 },
    { NULL, "LRxSubscriber;", 0x1, 5, 6, -1, 7, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithInt:);
  methods[1].selector = @selector(initWithInt:withId:);
  methods[2].selector = @selector(initWithInt:withId:withBoolean:);
  methods[3].selector = @selector(callWithId:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "index_", "I", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "hasDefault_", "Z", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
    { "defaultValue_", "LNSObject;", .constantValue.asLong = 0, 0x10, -1, -1, 8, -1 },
  };
  static const void *ptrTable[] = { "I", "ILNSObject;", "(ITT;)V", "ILNSObject;Z", "(ITT;Z)V", "call", "LRxSubscriber;", "(Lrx/Subscriber<-TT;>;)Lrx/Subscriber<-TT;>;", "TT;", "LRxInternalOperatorsOperatorElementAt_InnerProducer;", "<T:Ljava/lang/Object;>Ljava/lang/Object;Lrx/Observable$Operator<TT;TT;>;" };
  static const J2ObjcClassInfo _RxInternalOperatorsOperatorElementAt = { "OperatorElementAt", "rx.internal.operators", ptrTable, methods, fields, 7, 0x11, 4, 3, -1, 9, -1, 10, -1 };
  return &_RxInternalOperatorsOperatorElementAt;
}

@end

void RxInternalOperatorsOperatorElementAt_initWithInt_(RxInternalOperatorsOperatorElementAt *self, jint index) {
  RxInternalOperatorsOperatorElementAt_initWithInt_withId_withBoolean_(self, index, nil, false);
}

RxInternalOperatorsOperatorElementAt *new_RxInternalOperatorsOperatorElementAt_initWithInt_(jint index) {
  J2OBJC_NEW_IMPL(RxInternalOperatorsOperatorElementAt, initWithInt_, index)
}

RxInternalOperatorsOperatorElementAt *create_RxInternalOperatorsOperatorElementAt_initWithInt_(jint index) {
  J2OBJC_CREATE_IMPL(RxInternalOperatorsOperatorElementAt, initWithInt_, index)
}

void RxInternalOperatorsOperatorElementAt_initWithInt_withId_(RxInternalOperatorsOperatorElementAt *self, jint index, id defaultValue) {
  RxInternalOperatorsOperatorElementAt_initWithInt_withId_withBoolean_(self, index, defaultValue, true);
}

RxInternalOperatorsOperatorElementAt *new_RxInternalOperatorsOperatorElementAt_initWithInt_withId_(jint index, id defaultValue) {
  J2OBJC_NEW_IMPL(RxInternalOperatorsOperatorElementAt, initWithInt_withId_, index, defaultValue)
}

RxInternalOperatorsOperatorElementAt *create_RxInternalOperatorsOperatorElementAt_initWithInt_withId_(jint index, id defaultValue) {
  J2OBJC_CREATE_IMPL(RxInternalOperatorsOperatorElementAt, initWithInt_withId_, index, defaultValue)
}

void RxInternalOperatorsOperatorElementAt_initWithInt_withId_withBoolean_(RxInternalOperatorsOperatorElementAt *self, jint index, id defaultValue, jboolean hasDefault) {
  NSObject_init(self);
  if (index < 0) {
    @throw create_JavaLangIndexOutOfBoundsException_initWithNSString_(JreStrcat("I$", index, @" is out of bounds"));
  }
  self->index_ = index;
  JreStrongAssign(&self->defaultValue_, defaultValue);
  self->hasDefault_ = hasDefault;
}

RxInternalOperatorsOperatorElementAt *new_RxInternalOperatorsOperatorElementAt_initWithInt_withId_withBoolean_(jint index, id defaultValue, jboolean hasDefault) {
  J2OBJC_NEW_IMPL(RxInternalOperatorsOperatorElementAt, initWithInt_withId_withBoolean_, index, defaultValue, hasDefault)
}

RxInternalOperatorsOperatorElementAt *create_RxInternalOperatorsOperatorElementAt_initWithInt_withId_withBoolean_(jint index, id defaultValue, jboolean hasDefault) {
  J2OBJC_CREATE_IMPL(RxInternalOperatorsOperatorElementAt, initWithInt_withId_withBoolean_, index, defaultValue, hasDefault)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RxInternalOperatorsOperatorElementAt)

@implementation RxInternalOperatorsOperatorElementAt_InnerProducer

- (instancetype)initWithRxProducer:(id<RxProducer>)actual {
  RxInternalOperatorsOperatorElementAt_InnerProducer_initWithRxProducer_(self, actual);
  return self;
}

- (void)requestWithLong:(jlong)n {
  if (n < 0) {
    @throw create_JavaLangIllegalArgumentException_initWithNSString_(@"n >= 0 required");
  }
  if (n > 0 && [self compareAndSetWithBoolean:false withBoolean:true]) {
    [((id<RxProducer>) nil_chk(actual_)) requestWithLong:JavaLangLong_MAX_VALUE];
  }
}

- (void)dealloc {
  RELEASE_(actual_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 1, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithRxProducer:);
  methods[1].selector = @selector(requestWithLong:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "J", .constantValue.asLong = RxInternalOperatorsOperatorElementAt_InnerProducer_serialVersionUID, 0x1a, -1, -1, -1, -1 },
    { "actual_", "LRxProducer;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LRxProducer;", "request", "J", "LRxInternalOperatorsOperatorElementAt;" };
  static const J2ObjcClassInfo _RxInternalOperatorsOperatorElementAt_InnerProducer = { "InnerProducer", "rx.internal.operators", ptrTable, methods, fields, 7, 0x8, 2, 2, 3, -1, -1, -1, -1 };
  return &_RxInternalOperatorsOperatorElementAt_InnerProducer;
}

@end

void RxInternalOperatorsOperatorElementAt_InnerProducer_initWithRxProducer_(RxInternalOperatorsOperatorElementAt_InnerProducer *self, id<RxProducer> actual) {
  JavaUtilConcurrentAtomicAtomicBoolean_init(self);
  JreStrongAssign(&self->actual_, actual);
}

RxInternalOperatorsOperatorElementAt_InnerProducer *new_RxInternalOperatorsOperatorElementAt_InnerProducer_initWithRxProducer_(id<RxProducer> actual) {
  J2OBJC_NEW_IMPL(RxInternalOperatorsOperatorElementAt_InnerProducer, initWithRxProducer_, actual)
}

RxInternalOperatorsOperatorElementAt_InnerProducer *create_RxInternalOperatorsOperatorElementAt_InnerProducer_initWithRxProducer_(id<RxProducer> actual) {
  J2OBJC_CREATE_IMPL(RxInternalOperatorsOperatorElementAt_InnerProducer, initWithRxProducer_, actual)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RxInternalOperatorsOperatorElementAt_InnerProducer)

@implementation RxInternalOperatorsOperatorElementAt_$1

- (void)onNextWithId:(id)value {
  if (currentIndex_++ == this$0_->index_) {
    [((RxSubscriber *) nil_chk(val$child_)) onNextWithId:value];
    [val$child_ onCompleted];
    [self unsubscribe];
  }
}

- (void)onErrorWithNSException:(NSException *)e {
  [((RxSubscriber *) nil_chk(val$child_)) onErrorWithNSException:e];
}

- (void)onCompleted {
  if (currentIndex_ <= this$0_->index_) {
    if (this$0_->hasDefault_) {
      [((RxSubscriber *) nil_chk(val$child_)) onNextWithId:this$0_->defaultValue_];
      [val$child_ onCompleted];
    }
    else {
      [((RxSubscriber *) nil_chk(val$child_)) onErrorWithNSException:create_JavaLangIndexOutOfBoundsException_initWithNSString_(JreStrcat("I$", this$0_->index_, @" is out of bounds"))];
    }
  }
}

- (void)setProducerWithRxProducer:(id<RxProducer>)p {
  [((RxSubscriber *) nil_chk(val$child_)) setProducerWithRxProducer:create_RxInternalOperatorsOperatorElementAt_InnerProducer_initWithRxProducer_(p)];
}

- (instancetype)initWithRxInternalOperatorsOperatorElementAt:(RxInternalOperatorsOperatorElementAt *)outer$
                                            withRxSubscriber:(RxSubscriber *)capture$0 {
  RxInternalOperatorsOperatorElementAt_$1_initWithRxInternalOperatorsOperatorElementAt_withRxSubscriber_(self, outer$, capture$0);
  return self;
}

- (void)dealloc {
  RELEASE_(this$0_);
  RELEASE_(val$child_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x1, 0, 1, -1, 2, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 5, 6, -1, -1, -1, -1 },
    { NULL, NULL, 0x0, -1, 7, -1, 8, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(onNextWithId:);
  methods[1].selector = @selector(onErrorWithNSException:);
  methods[2].selector = @selector(onCompleted);
  methods[3].selector = @selector(setProducerWithRxProducer:);
  methods[4].selector = @selector(initWithRxInternalOperatorsOperatorElementAt:withRxSubscriber:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LRxInternalOperatorsOperatorElementAt;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "currentIndex_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "val$child_", "LRxSubscriber;", .constantValue.asLong = 0, 0x1012, -1, -1, 9, -1 },
  };
  static const void *ptrTable[] = { "onNext", "LNSObject;", "(TT;)V", "onError", "LNSException;", "setProducer", "LRxProducer;", "LRxInternalOperatorsOperatorElementAt;LRxSubscriber;", "(Lrx/internal/operators/OperatorElementAt;Lrx/Subscriber<-TT;>;)V", "Lrx/Subscriber<-TT;>;", "LRxInternalOperatorsOperatorElementAt;", "callWithId:", "Lrx/Subscriber<TT;>;" };
  static const J2ObjcClassInfo _RxInternalOperatorsOperatorElementAt_$1 = { "", "rx.internal.operators", ptrTable, methods, fields, 7, 0x8008, 5, 3, 10, -1, 11, 12, -1 };
  return &_RxInternalOperatorsOperatorElementAt_$1;
}

@end

void RxInternalOperatorsOperatorElementAt_$1_initWithRxInternalOperatorsOperatorElementAt_withRxSubscriber_(RxInternalOperatorsOperatorElementAt_$1 *self, RxInternalOperatorsOperatorElementAt *outer$, RxSubscriber *capture$0) {
  JreStrongAssign(&self->this$0_, outer$);
  JreStrongAssign(&self->val$child_, capture$0);
  RxSubscriber_init(self);
}

RxInternalOperatorsOperatorElementAt_$1 *new_RxInternalOperatorsOperatorElementAt_$1_initWithRxInternalOperatorsOperatorElementAt_withRxSubscriber_(RxInternalOperatorsOperatorElementAt *outer$, RxSubscriber *capture$0) {
  J2OBJC_NEW_IMPL(RxInternalOperatorsOperatorElementAt_$1, initWithRxInternalOperatorsOperatorElementAt_withRxSubscriber_, outer$, capture$0)
}

RxInternalOperatorsOperatorElementAt_$1 *create_RxInternalOperatorsOperatorElementAt_$1_initWithRxInternalOperatorsOperatorElementAt_withRxSubscriber_(RxInternalOperatorsOperatorElementAt *outer$, RxSubscriber *capture$0) {
  J2OBJC_CREATE_IMPL(RxInternalOperatorsOperatorElementAt_$1, initWithRxInternalOperatorsOperatorElementAt_withRxSubscriber_, outer$, capture$0)
}
