//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/RxJava/src/main/java/rx/observers/SafeCompletableSubscriber.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RxObserversSafeCompletableSubscriber")
#ifdef RESTRICT_RxObserversSafeCompletableSubscriber
#define INCLUDE_ALL_RxObserversSafeCompletableSubscriber 0
#else
#define INCLUDE_ALL_RxObserversSafeCompletableSubscriber 1
#endif
#undef RESTRICT_RxObserversSafeCompletableSubscriber

#if !defined (RxObserversSafeCompletableSubscriber_) && (INCLUDE_ALL_RxObserversSafeCompletableSubscriber || defined(INCLUDE_RxObserversSafeCompletableSubscriber))
#define RxObserversSafeCompletableSubscriber_

#define RESTRICT_RxCompletableSubscriber 1
#define INCLUDE_RxCompletableSubscriber 1
#include "RxCompletableSubscriber.h"

#define RESTRICT_RxSubscription 1
#define INCLUDE_RxSubscription 1
#include "RxSubscription.h"

@interface RxObserversSafeCompletableSubscriber : NSObject < RxCompletableSubscriber, RxSubscription > {
 @public
  id<RxCompletableSubscriber> actual_;
  id<RxSubscription> s_;
  jboolean done_;
}

#pragma mark Public

- (instancetype)initWithRxCompletableSubscriber:(id<RxCompletableSubscriber>)actual;

- (jboolean)isUnsubscribed;

- (void)onCompleted;

- (void)onErrorWithNSException:(NSException *)e;

- (void)onSubscribeWithRxSubscription:(id<RxSubscription>)d;

- (void)unsubscribe;

@end

J2OBJC_EMPTY_STATIC_INIT(RxObserversSafeCompletableSubscriber)

J2OBJC_FIELD_SETTER(RxObserversSafeCompletableSubscriber, actual_, id<RxCompletableSubscriber>)
J2OBJC_FIELD_SETTER(RxObserversSafeCompletableSubscriber, s_, id<RxSubscription>)

FOUNDATION_EXPORT void RxObserversSafeCompletableSubscriber_initWithRxCompletableSubscriber_(RxObserversSafeCompletableSubscriber *self, id<RxCompletableSubscriber> actual);

FOUNDATION_EXPORT RxObserversSafeCompletableSubscriber *new_RxObserversSafeCompletableSubscriber_initWithRxCompletableSubscriber_(id<RxCompletableSubscriber> actual) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxObserversSafeCompletableSubscriber *create_RxObserversSafeCompletableSubscriber_initWithRxCompletableSubscriber_(id<RxCompletableSubscriber> actual);

J2OBJC_TYPE_LITERAL_HEADER(RxObserversSafeCompletableSubscriber)

#endif

#pragma pop_macro("INCLUDE_ALL_RxObserversSafeCompletableSubscriber")
