/**
 * Created by kgalligan on 11/6/16.
 */

public class TestResources
{
    public static final String fulllist = "rx/exceptions/CompositeExceptionTest.java\n" +
            "rx/exceptions/ExceptionsNullTest.java\n" +
            "rx/exceptions/ExceptionsTest.java\n" +
            "rx/exceptions/OnNextValueTest.java\n" +
            "rx/functions/ActionsTest.java\n" +
            "rx/functions/FunctionsTest.java\n" +
            "rx/internal/operators/BackpressureUtilsTest.java\n" +
            "rx/internal/operators/BlockingOperatorLatestTest.java\n" +
            "rx/internal/operators/BlockingOperatorMostRecentTest.java\n" +
            "rx/internal/operators/BlockingOperatorNextTest.java\n" +
            "rx/internal/operators/BlockingOperatorToFutureTest.java\n" +
            "rx/internal/operators/BlockingOperatorToIteratorTest.java\n" +
            "rx/internal/operators/CachedObservableTest.java\n" +
            "rx/internal/operators/CompletableFromEmitterTest.java\n" +
            "rx/internal/operators/DeferredScalarSubscriberTest.java\n" +
            "rx/internal/operators/InternalSafeSubscriberTest.java\n" +
            "rx/internal/operators/NotificationLiteTest.java\n" +
            "rx/internal/operators/OnSubscribeAmbTest.java\n" +
            "rx/internal/operators/OnSubscribeCollectTest.java\n" +
            "rx/internal/operators/OnSubscribeCombineLatestTest.java\n" +
            "rx/internal/operators/OnSubscribeCompletableTest.java\n" +
            "rx/internal/operators/OnSubscribeConcatDelayErrorTest.java\n" +
            "rx/internal/operators/OnSubscribeDeferTest.java\n" +
            "rx/internal/operators/OnSubscribeDelaySubscriptionOtherTest.java\n" +
            "rx/internal/operators/OnSubscribeDetachTest.java\n" +
            "rx/internal/operators/OnSubscribeDoOnEachTest.java\n" +
            "rx/internal/operators/OnSubscribeFilterTest.java\n" +
            "rx/internal/operators/OnSubscribeFlattenIterableTest.java\n" +
            "rx/internal/operators/OnSubscribeFromArrayTest.java\n" +
            "rx/internal/operators/OnSubscribeFromAsyncEmitterTest.java\n" +
            "rx/internal/operators/OnSubscribeFromCallableTest.java\n" +
            "rx/internal/operators/OnSubscribeFromEmitterTest.java\n" +
            "rx/internal/operators/OnSubscribeFromIterableTest.java\n" +
            "rx/internal/operators/OnSubscribeGroupJoinTest.java\n" +
            "rx/internal/operators/OnSubscribeJoinTest.java\n" +
            "rx/internal/operators/OnSubscribeMapTest.java\n" +
            "rx/internal/operators/OnSubscribeRangeTest.java\n" +
            "rx/internal/operators/OnSubscribeReduceTest.java\n" +
            "rx/internal/operators/OnSubscribeRefCountTest.java\n" +
            "rx/internal/operators/OnSubscribeSingleTest.java\n" +
            "rx/internal/operators/OnSubscribeTimerTest.java\n" +
            "rx/internal/operators/OnSubscribeToMapTest.java\n" +
            "rx/internal/operators/OnSubscribeToMultimapTest.java\n" +
            "rx/internal/operators/OnSubscribeToObservableFutureTest.java\n" +
            "rx/internal/operators/OnSubscribeUsingTest.java\n" +
            "rx/internal/operators/OperatorAllTest.java\n" +
            "rx/internal/operators/OperatorAnyTest.java\n" +
            "rx/internal/operators/OperatorAsObservableTest.java\n" +
            "rx/internal/operators/OperatorBufferTest.java\n" +
            "rx/internal/operators/OperatorCastTest.java\n" +
            "rx/internal/operators/OperatorConcatTest.java\n" +
            "rx/internal/operators/OperatorCountTest.java\n" +
            "rx/internal/operators/OperatorDebounceTest.java\n" +
            "rx/internal/operators/OperatorDefaultIfEmptyTest.java\n" +
            "rx/internal/operators/OperatorDelayTest.java\n" +
            "rx/internal/operators/OperatorDematerializeTest.java\n" +
            "rx/internal/operators/OperatorDistinctTest.java\n" +
            "rx/internal/operators/OperatorDistinctUntilChangedTest.java\n" +
            "rx/internal/operators/OperatorDoAfterTerminateTest.java\n" +
            "rx/internal/operators/OperatorDoOnRequestTest.java\n" +
            "rx/internal/operators/OperatorDoOnSubscribeTest.java\n" +
            "rx/internal/operators/OperatorDoOnUnsubscribeTest.java\n" +
            "rx/internal/operators/OperatorEagerConcatMapTest.java\n" +
            "rx/internal/operators/OperatorElementAtTest.java\n" +
            "rx/internal/operators/OperatorFirstTest.java\n" +
            "rx/internal/operators/OperatorFlatMapTest.java\n" +
            "rx/internal/operators/OperatorGroupByTest.java\n" +
            "rx/internal/operators/OperatorIgnoreElementsTest.java\n" +
            "rx/internal/operators/OperatorLastTest.java\n" +
            "rx/internal/operators/OperatorMapNotificationTest.java\n" +
            "rx/internal/operators/OperatorMapPairTest.java\n" +
            "rx/internal/operators/OperatorMaterializeTest.java\n" +
            "rx/internal/operators/OperatorMergeDelayErrorTest.java\n" +
            "rx/internal/operators/OperatorMergeMaxConcurrentTest.java\n" +
            "rx/internal/operators/OperatorMergeTest.java\n" +
            "rx/internal/operators/OperatorMulticastTest.java\n" +
            "rx/internal/operators/OperatorObserveOnTest.java\n" +
            "rx/internal/operators/OperatorOnBackpressureBufferTest.java\n" +
            "rx/internal/operators/OperatorOnBackpressureDropTest.java\n" +
            "rx/internal/operators/OperatorOnBackpressureLatestTest.java\n" +
            "rx/internal/operators/OperatorOnErrorResumeNextViaFunctionTest.java\n" +
            "rx/internal/operators/OperatorOnErrorResumeNextViaObservableTest.java\n" +
            "rx/internal/operators/OperatorOnErrorReturnTest.java\n" +
            "rx/internal/operators/OperatorOnExceptionResumeNextViaObservableTest.java\n" +
            "rx/internal/operators/OperatorPublishFunctionTest.java\n" +
            "rx/internal/operators/OperatorPublishTest.java\n" +
            "rx/internal/operators/OperatorRepeatTest.java\n" +
            "rx/internal/operators/OperatorReplayTest.java\n" +
            "rx/internal/operators/OperatorRetryTest.java\n" +
            "rx/internal/operators/OperatorRetryWithPredicateTest.java\n" +
            "rx/internal/operators/OperatorSampleTest.java\n" +
            "rx/internal/operators/OperatorScanTest.java\n" +
            "rx/internal/operators/OperatorSequenceEqualTest.java\n" +
            "rx/internal/operators/OperatorSerializeTest.java\n" +
            "rx/internal/operators/OperatorSingleTest.java\n" +
            "rx/internal/operators/OperatorSkipLastTest.java\n" +
            "rx/internal/operators/OperatorSkipLastTimedTest.java\n" +
            "rx/internal/operators/OperatorSkipTest.java\n" +
            "rx/internal/operators/OperatorSkipTimedTest.java\n" +
            "rx/internal/operators/OperatorSkipUntilTest.java\n" +
            "rx/internal/operators/OperatorSkipWhileTest.java\n" +
            "rx/internal/operators/OperatorSubscribeOnTest.java\n" +
            "rx/internal/operators/OperatorSwitchIfEmptyTest.java\n" +
            "rx/internal/operators/OperatorSwitchTest.java\n" +
            "rx/internal/operators/OperatorTakeLastOneTest.java\n" +
            "rx/internal/operators/OperatorTakeLastTest.java\n" +
            "rx/internal/operators/OperatorTakeLastTimedTest.java\n" +
            "rx/internal/operators/OperatorTakeTest.java\n" +
            "rx/internal/operators/OperatorTakeTimedTest.java\n" +
            "rx/internal/operators/OperatorTakeUntilPredicateTest.java\n" +
            "rx/internal/operators/OperatorTakeUntilTest.java\n" +
            "rx/internal/operators/OperatorTakeWhileTest.java\n" +
            "rx/internal/operators/OperatorThrottleFirstTest.java\n" +
            "rx/internal/operators/OperatorTimeIntervalTest.java\n" +
            "rx/internal/operators/OperatorTimeoutTests.java\n" +
            "rx/internal/operators/OperatorTimeoutWithSelectorTest.java\n" +
            "rx/internal/operators/OperatorTimestampTest.java\n" +
            "rx/internal/operators/OperatorToObservableListTest.java\n" +
            "rx/internal/operators/OperatorToObservableSortedListTest.java\n" +
            "rx/internal/operators/OperatorUnsubscribeOnTest.java\n" +
            "rx/internal/operators/OperatorWindowWithObservableTest.java\n" +
            "rx/internal/operators/OperatorWindowWithSizeTest.java\n" +
            "rx/internal/operators/OperatorWindowWithStartEndObservableTest.java\n" +
            "rx/internal/operators/OperatorWindowWithTimeTest.java\n" +
            "rx/internal/operators/OperatorWithLatestFromTest.java\n" +
            "rx/internal/operators/OperatorZipCompletionTest.java\n" +
            "rx/internal/operators/OperatorZipIterableTest.java\n" +
            "rx/internal/operators/OperatorZipTest.java\n" +
            "rx/internal/operators/SingleDoAfterTerminateTest.java\n" +
            "rx/internal/operators/SingleOnSubscribeDelaySubscriptionOtherTest.java\n" +
            "rx/internal/operators/SingleOnSubscribeUsingTest.java\n" +
            "rx/internal/operators/SingleOperatorZipTest.java\n" +
            "rx/internal/producers/ProducerArbiterTest.java\n" +
            "rx/internal/producers/ProducerObserverArbiterTest.java\n" +
            "rx/internal/producers/ProducersTest.java\n" +
            "rx/internal/producers/SingleDelayedProducerTest.java\n" +
            "rx/internal/producers/SingleProducerTest.java\n" +
            "rx/internal/schedulers/ExecutorSchedulerTest.java\n" +
            "rx/internal/schedulers/InternalGenericScheduledExecutorServiceTest.java\n" +
            "rx/internal/schedulers/NewThreadWorkerTest.java\n" +
            "rx/internal/util/unsafe/Pow2Test.java\n" +
            "rx/internal/util/unsafe/UnsafeAccessTest.java\n" +
            "rx/internal/util/BlockingUtilsTest.java\n" +
            "rx/internal/util/ExceptionUtilsTest.java\n" +
            "rx/internal/util/IndexedRingBufferTest.java\n" +
            "rx/internal/util/JCToolsQueueTests.java\n" +
            "rx/internal/util/LinkedArrayListTest.java\n" +
            "rx/internal/util/OpenHashSetTest.java\n" +
            "rx/internal/util/PlatformDependentTest.java\n" +
            "rx/internal/util/RxRingBufferSpmcTest.java\n" +
            "rx/internal/util/RxRingBufferSpscTest.java\n" +
            "rx/internal/util/RxRingBufferWithoutUnsafeTest.java\n" +
            "rx/internal/util/ScalarSynchronousObservableTest.java\n" +
            "rx/internal/util/ScalarSynchronousSingleTest.java\n" +
            "rx/internal/util/SubscriptionListTest.java\n" +
            "rx/internal/util/SynchronizedQueueTest.java\n" +
            "rx/internal/util/UtilityFunctionsTest.java\n" +
            "rx/observables/AsyncOnSubscribeTest.java\n" +
            "rx/observables/BlockingObservableTest.java\n" +
            "rx/observables/ConnectableObservableTest.java\n" +
            "rx/observables/SyncOnSubscribeTest.java\n" +
            "rx/observers/AsyncCompletableSubscriberTest.java\n" +
            "rx/observers/CompletableSubscriberTest.java\n" +
            "rx/observers/ObserversTest.java\n" +
            "rx/observers/SafeObserverTest.java\n" +
            "rx/observers/SafeSubscriberTest.java\n" +
            "rx/observers/SerializedObserverTest.java\n" +
            "rx/observers/SubscribersTest.java\n" +
            "rx/observers/TestObserverTest.java\n" +
            "rx/observers/TestSubscriberTest.java\n" +
            "rx/plugins/RxJavaHooksTest.java\n" +
            "rx/plugins/RxJavaPluginsTest.java\n" +
            "rx/plugins/RxJavaSchedulersHookTest.java\n" +
            "rx/schedulers/ComputationSchedulerTests.java\n" +
            "rx/schedulers/DeprecatedSchedulersTest.java\n" +
            "rx/schedulers/GenericScheduledExecutorServiceTest.java\n" +
            "rx/schedulers/ImmediateSchedulerTest.java\n" +
            "rx/schedulers/IoSchedulerTest.java\n" +
            "rx/schedulers/NewThreadSchedulerTest.java\n" +
            "rx/schedulers/ResetSchedulersTest.java\n" +
            "rx/schedulers/SchedulerLifecycleTest.java\n" +
            "rx/schedulers/SchedulerTests.java\n" +
            "rx/schedulers/SchedulerWhenTest.java\n" +
            "rx/schedulers/TestSchedulerTest.java\n" +
            "rx/schedulers/TimeXTest.java\n" +
            "rx/schedulers/TrampolineSchedulerTest.java\n" +
            "rx/singles/BlockingSingleTest.java\n" +
            "rx/subjects/AsyncSubjectTest.java\n" +
            "rx/subjects/BehaviorSubjectTest.java\n" +
            "rx/subjects/BufferUntilSubscriberTest.java\n" +
            "rx/subjects/PublishSubjectTest.java\n" +
            "rx/subjects/ReplaySubjectBoundedConcurrencyTest.java\n" +
            "rx/subjects/ReplaySubjectConcurrencyTest.java\n" +
            "rx/subjects/ReplaySubjectTest.java\n" +
            "rx/subjects/SerializedSubjectTest.java\n" +
            "rx/subjects/TestSubjectTest.java\n" +
            "rx/subscriptions/CompositeSubscriptionTest.java\n" +
            "rx/subscriptions/MultipleAssignmentSubscriptionTest.java\n" +
            "rx/subscriptions/RefCountSubscriptionTest.java\n" +
            "rx/subscriptions/SerialSubscriptionTests.java\n" +
            "rx/subscriptions/SubscriptionsTest.java\n" +
            "rx/test/TestObstructionDetectionTest.java\n" +
            "rx/util/AssertObservableTest.java\n" +
            "rx/BackpressureTests.java\n" +
            "rx/CombineLatestTests.java\n" +
            "rx/CompletableTest.java\n" +
            "rx/ConcatTests.java\n" +
            "rx/CovarianceTest.java\n" +
            "rx/ErrorHandlingTests.java\n" +
            "rx/EventStreamTest.java\n" +
            "rx/GroupByTests.java\n" +
            "rx/MergeTests.java\n" +
            "rx/NotificationTest.java\n" +
            "rx/ObservableDoOnTest.java\n" +
            "rx/ObservableTests.java\n" +
            "rx/ObservableWindowTests.java\n" +
            "rx/ReduceTests.java\n" +
            "rx/ScanTests.java\n" +
            "rx/SchedulerWorkerTest.java\n" +
            "rx/SingleTest.java\n" +
            "rx/StartWithTests.java\n" +
            "rx/SubscriberTest.java\n" +
            "rx/ThrottleLastTests.java\n" +
            "rx/ThrottleWithTimeoutTests.java\n" +
            "rx/ZipTests.java";
}
