//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/RxJava/src/main/java/rx/plugins/RxJavaSingleExecutionHookDefault.java
//

#include "J2ObjC_source.h"
#include "RxPluginsRxJavaSingleExecutionHook.h"
#include "RxPluginsRxJavaSingleExecutionHookDefault.h"

@interface RxPluginsRxJavaSingleExecutionHookDefault ()

- (instancetype)init;

@end

inline RxPluginsRxJavaSingleExecutionHookDefault *RxPluginsRxJavaSingleExecutionHookDefault_get_INSTANCE();
static RxPluginsRxJavaSingleExecutionHookDefault *RxPluginsRxJavaSingleExecutionHookDefault_INSTANCE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(RxPluginsRxJavaSingleExecutionHookDefault, INSTANCE, RxPluginsRxJavaSingleExecutionHookDefault *)

__attribute__((unused)) static void RxPluginsRxJavaSingleExecutionHookDefault_init(RxPluginsRxJavaSingleExecutionHookDefault *self);

__attribute__((unused)) static RxPluginsRxJavaSingleExecutionHookDefault *new_RxPluginsRxJavaSingleExecutionHookDefault_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static RxPluginsRxJavaSingleExecutionHookDefault *create_RxPluginsRxJavaSingleExecutionHookDefault_init();

J2OBJC_INITIALIZED_DEFN(RxPluginsRxJavaSingleExecutionHookDefault)

@implementation RxPluginsRxJavaSingleExecutionHookDefault

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  RxPluginsRxJavaSingleExecutionHookDefault_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (RxPluginsRxJavaSingleExecutionHook *)getInstance {
  return RxPluginsRxJavaSingleExecutionHookDefault_getInstance();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LRxPluginsRxJavaSingleExecutionHook;", 0x9, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getInstance);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "INSTANCE", "LRxPluginsRxJavaSingleExecutionHookDefault;", .constantValue.asLong = 0, 0x1a, -1, 0, -1, -1 },
  };
  static const void *ptrTable[] = { &RxPluginsRxJavaSingleExecutionHookDefault_INSTANCE };
  static const J2ObjcClassInfo _RxPluginsRxJavaSingleExecutionHookDefault = { "RxJavaSingleExecutionHookDefault", "rx.plugins", ptrTable, methods, fields, 7, 0x10, 2, 1, -1, -1, -1, -1, -1 };
  return &_RxPluginsRxJavaSingleExecutionHookDefault;
}

+ (void)initialize {
  if (self == [RxPluginsRxJavaSingleExecutionHookDefault class]) {
    JreStrongAssignAndConsume(&RxPluginsRxJavaSingleExecutionHookDefault_INSTANCE, new_RxPluginsRxJavaSingleExecutionHookDefault_init());
    J2OBJC_SET_INITIALIZED(RxPluginsRxJavaSingleExecutionHookDefault)
  }
}

@end

void RxPluginsRxJavaSingleExecutionHookDefault_init(RxPluginsRxJavaSingleExecutionHookDefault *self) {
  RxPluginsRxJavaSingleExecutionHook_init(self);
}

RxPluginsRxJavaSingleExecutionHookDefault *new_RxPluginsRxJavaSingleExecutionHookDefault_init() {
  J2OBJC_NEW_IMPL(RxPluginsRxJavaSingleExecutionHookDefault, init)
}

RxPluginsRxJavaSingleExecutionHookDefault *create_RxPluginsRxJavaSingleExecutionHookDefault_init() {
  J2OBJC_CREATE_IMPL(RxPluginsRxJavaSingleExecutionHookDefault, init)
}

RxPluginsRxJavaSingleExecutionHook *RxPluginsRxJavaSingleExecutionHookDefault_getInstance() {
  RxPluginsRxJavaSingleExecutionHookDefault_initialize();
  return RxPluginsRxJavaSingleExecutionHookDefault_INSTANCE;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RxPluginsRxJavaSingleExecutionHookDefault)
