# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Preview-JDKs

on:
  push:
    branches: [ '4.x' ]
  pull_request:
    branches: [ '4.x' ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        jdk: [27]   # add 28-ea etc. later

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Set up JDK 26
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        distribution: 'zulu'
        java-version: '26'
        cache: gradle

    - name: Set up JDK ${{ matrix.jdk }}-ea
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        distribution: 'temurin'
        java-version: '${{ matrix.jdk }}-ea'

    - name: Cache Gradle packages
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle-${{ secrets.CACHE_VERSION }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Validity Tests Upfront
      env:
        JDK_EXPERIMENTAL: ${{ matrix.jdk }}
        JAVA_HOME: ${{ env.JAVA_HOME_26_X64 }}
      run: ./gradlew test --tests "io.reactivex.rxjava4.validators.*" --stacktrace --no-daemon
    - name: Build RxJava
      env:
        JDK_EXPERIMENTAL: ${{ matrix.jdk }}
        JAVA_HOME: ${{ env.JAVA_HOME_26_X64 }}
      run: ./gradlew build --stacktrace
    - name: Generate Javadoc
      env:
        JDK_EXPERIMENTAL: ${{ matrix.jdk }}
        JAVA_HOME: ${{ env.JAVA_HOME_26_X64 }}
      run: ./gradlew javadoc --stacktrace

