# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Snapshot

on:
  push:
    branches: [ '4.x' ]
    
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'ReactiveX/RxJava'
    env:
      # ------------------------------------------------------------------------------ 
      CI_BUILD_NUMBER: ${{ github.run_number }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Set up JDK 26
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        distribution: 'zulu'
        java-version: '26'
    - name: Cache Gradle packages
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle-${{ secrets.CACHE_VERSION }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Validity Tests Upfront
      run: ./gradlew test --tests "io.reactivex.rxjava4.validators.*" --stacktrace --no-daemon
    - name: Build RxJava
      run: ./gradlew build --stacktrace --no-daemon

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
      if: always()                      # important: run even if tests failed
      with:
        files: |
          **/build/test-results/**/TEST-*.xml
          **/build/test-results/**/*.xml
          **/build/test-results/testNG/TEST-*.xml
        check_run: false
        comment_mode: failures
        fail_on: test failures
        check_name: "🧪 RxJava Test Results"
        report_individual_runs: true

    - name: Upload to Codecov  
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  prerelease:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CI_BUILD_NUMBER: ${{ github.run_number }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Set up JDK 26
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        distribution: 'zulu'
        java-version: '26'
    - name: Cache Gradle packages
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle-${{ secrets.CACHE_VERSION }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Grant execute permission for push
      run: chmod +x push_javadoc.sh
    - name: Upload Snapshot
      run: ./gradlew -PreleaseMode=branch publishAllPublicationsToMavenCentralRepository --no-daemon --no-parallel --stacktrace
      env:
        # Define secrets at https://github.com/ReactiveX/RxJava/settings/secrets/actions
        # ------------------------------------------------------------------------------ 
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USER }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
    - name: Push Javadoc
      run: ./push_javadoc.sh
        # Define secrets at https://github.com/ReactiveX/RxJava/settings/secrets/actions
        # ------------------------------------------------------------------------------
      env:
        JAVADOCS_TOKEN: ${{ secrets.JAVADOCS_TOKEN }}
